#include <stdio.h>
typedef void TestFn(void);
typedef struct{
	char* name; 
	TestFn* fn;
} Test;

//code to be updated starts
TestFn setup,teardown,fixtureSetup,fixtureTearDown,test_createList_creates_a_new_linked_list,test_create_node_creates_a_new_node_with_int_data,test_create_node_creates_a_new_node_with_char_data,test_create_node_creates_a_new_node_with_float_data,test_add_to_list_add_a_new_node_in_a_previously_created_linked_list,test_add_to_list_add_two_new_node_in_a_previously_created_linked_list,test_add_to_list_add_a_NULL_node_in_a_previously_created_linked_list,test_add_to_list_add_one_new_NULL_node_and_one_new_node_with_data_in_a_previously_created_linked_list,test_get_first_element_returns_the_data_in_head_of_a_previously_created_linked_list,test_get_firstst_element_returns_the_data_in_head_of_a_previously_created_linked_list_with_float_element,test_get_last_element_returns_the_data_in_tail_of_a_previously_created_linked_list,test_get_last_element_returns_the_data_in_tail_of_a_previously_created_linked_list_with_float_element,test_tarverse_increased_two_elements_by_one_in_a_linked_list,test_tarverse_increased_three_elements_by_one_in_a_linked_list,test_tarverse_change_char_elements_into_uppercase_of_a_linked_list,test_tarverse_change_float_elements_into_its_float_value_of_a_linked_list,test_tarverse_change_double_elements_into_its_float_value_of_a_linked_list,test_tarverse_change_String_elements_into_its_float_value_of_a_linked_list,test_getElementAt_returns_the_first_element_of_list,test_getElementAt_returns_the_second_element_of_list,test_getElementAt_returns_the_second_element_of_list_of_floating_point_numbers,test_getElementAt_returns_the_second_element_of_list_of_characters,test_getElementAt_returns_the_second_element_of_list_of_strings,test_indexOf_gives_0_when_element_is_present_at_first_position_in_int_data_type,test_indexOf_gives_1_when_element_is_present_at_first_position_in_float_data_type,test_indexOf_gives_1_when_element_is_present_at_first_position_in_char_data_type,test_indexOf_gives_1_when_element_is_present_at_first_position_in_string_data_type,test_indexOf_gives_minus_1_when_element_is_not_present_in_int_data_type,test_deleteElementAt_0_deletes_the_first_element,test_deleteElementAt_2_deletes_the_last_element,test_deleteElementAt_1_deletes_the_second_element,test_deleteElementAt_returns_NULL__when_index_is_less_than_zero,test_deleteElementAt_returns_NULL__when_index_is_equal_with_count,test_deleteElementAt_returns_NULL_when_index_is_greater_than_count,test_deleteElementAt_returns_NULL_when_count_is_zero,test_deleteElementAt_list_will_be_empty_if_there_is_only_one_node,test_deleteElementAt_after_deletion_head_tail_points_to_a_single_node_1,test_deleteElementAt_after_deletion_head_tail_points_to_a_single_node_2,test_asArray_filled_an_array_with_the_integer_elements_of_a_linked_list,test_filter_returns_a_linked_list_populets_with_positive_data,test_filter_gives_list_of_even_numbers;
Test test[] = {"test_createList_creates_a_new_linked_list",test_createList_creates_a_new_linked_list,"test_create_node_creates_a_new_node_with_int_data",test_create_node_creates_a_new_node_with_int_data,"test_create_node_creates_a_new_node_with_char_data",test_create_node_creates_a_new_node_with_char_data,"test_create_node_creates_a_new_node_with_float_data",test_create_node_creates_a_new_node_with_float_data,"test_add_to_list_add_a_new_node_in_a_previously_created_linked_list",test_add_to_list_add_a_new_node_in_a_previously_created_linked_list,"test_add_to_list_add_two_new_node_in_a_previously_created_linked_list",test_add_to_list_add_two_new_node_in_a_previously_created_linked_list,"test_add_to_list_add_a_NULL_node_in_a_previously_created_linked_list",test_add_to_list_add_a_NULL_node_in_a_previously_created_linked_list,"test_add_to_list_add_one_new_NULL_node_and_one_new_node_with_data_in_a_previously_created_linked_list",test_add_to_list_add_one_new_NULL_node_and_one_new_node_with_data_in_a_previously_created_linked_list,"test_get_first_element_returns_the_data_in_head_of_a_previously_created_linked_list",test_get_first_element_returns_the_data_in_head_of_a_previously_created_linked_list,"test_get_firstst_element_returns_the_data_in_head_of_a_previously_created_linked_list_with_float_element",test_get_firstst_element_returns_the_data_in_head_of_a_previously_created_linked_list_with_float_element,"test_get_last_element_returns_the_data_in_tail_of_a_previously_created_linked_list",test_get_last_element_returns_the_data_in_tail_of_a_previously_created_linked_list,"test_get_last_element_returns_the_data_in_tail_of_a_previously_created_linked_list_with_float_element",test_get_last_element_returns_the_data_in_tail_of_a_previously_created_linked_list_with_float_element,"test_tarverse_increased_two_elements_by_one_in_a_linked_list",test_tarverse_increased_two_elements_by_one_in_a_linked_list,"test_tarverse_increased_three_elements_by_one_in_a_linked_list",test_tarverse_increased_three_elements_by_one_in_a_linked_list,"test_tarverse_change_char_elements_into_uppercase_of_a_linked_list",test_tarverse_change_char_elements_into_uppercase_of_a_linked_list,"test_tarverse_change_float_elements_into_its_float_value_of_a_linked_list",test_tarverse_change_float_elements_into_its_float_value_of_a_linked_list,"test_tarverse_change_double_elements_into_its_float_value_of_a_linked_list",test_tarverse_change_double_elements_into_its_float_value_of_a_linked_list,"test_tarverse_change_String_elements_into_its_float_value_of_a_linked_list",test_tarverse_change_String_elements_into_its_float_value_of_a_linked_list,"test_getElementAt_returns_the_first_element_of_list",test_getElementAt_returns_the_first_element_of_list,"test_getElementAt_returns_the_second_element_of_list",test_getElementAt_returns_the_second_element_of_list,"test_getElementAt_returns_the_second_element_of_list_of_floating_point_numbers",test_getElementAt_returns_the_second_element_of_list_of_floating_point_numbers,"test_getElementAt_returns_the_second_element_of_list_of_characters",test_getElementAt_returns_the_second_element_of_list_of_characters,"test_getElementAt_returns_the_second_element_of_list_of_strings",test_getElementAt_returns_the_second_element_of_list_of_strings,"test_indexOf_gives_0_when_element_is_present_at_first_position_in_int_data_type",test_indexOf_gives_0_when_element_is_present_at_first_position_in_int_data_type,"test_indexOf_gives_1_when_element_is_present_at_first_position_in_float_data_type",test_indexOf_gives_1_when_element_is_present_at_first_position_in_float_data_type,"test_indexOf_gives_1_when_element_is_present_at_first_position_in_char_data_type",test_indexOf_gives_1_when_element_is_present_at_first_position_in_char_data_type,"test_indexOf_gives_1_when_element_is_present_at_first_position_in_string_data_type",test_indexOf_gives_1_when_element_is_present_at_first_position_in_string_data_type,"test_indexOf_gives_minus_1_when_element_is_not_present_in_int_data_type",test_indexOf_gives_minus_1_when_element_is_not_present_in_int_data_type,"test_deleteElementAt_0_deletes_the_first_element",test_deleteElementAt_0_deletes_the_first_element,"test_deleteElementAt_2_deletes_the_last_element",test_deleteElementAt_2_deletes_the_last_element,"test_deleteElementAt_1_deletes_the_second_element",test_deleteElementAt_1_deletes_the_second_element,"test_deleteElementAt_returns_NULL__when_index_is_less_than_zero",test_deleteElementAt_returns_NULL__when_index_is_less_than_zero,"test_deleteElementAt_returns_NULL__when_index_is_equal_with_count",test_deleteElementAt_returns_NULL__when_index_is_equal_with_count,"test_deleteElementAt_returns_NULL_when_index_is_greater_than_count",test_deleteElementAt_returns_NULL_when_index_is_greater_than_count,"test_deleteElementAt_returns_NULL_when_count_is_zero",test_deleteElementAt_returns_NULL_when_count_is_zero,"test_deleteElementAt_list_will_be_empty_if_there_is_only_one_node",test_deleteElementAt_list_will_be_empty_if_there_is_only_one_node,"test_deleteElementAt_after_deletion_head_tail_points_to_a_single_node_1",test_deleteElementAt_after_deletion_head_tail_points_to_a_single_node_1,"test_deleteElementAt_after_deletion_head_tail_points_to_a_single_node_2",test_deleteElementAt_after_deletion_head_tail_points_to_a_single_node_2,"test_asArray_filled_an_array_with_the_integer_elements_of_a_linked_list",test_asArray_filled_an_array_with_the_integer_elements_of_a_linked_list,"test_filter_returns_a_linked_list_populets_with_positive_data",test_filter_returns_a_linked_list_populets_with_positive_data,"test_filter_gives_list_of_even_numbers",test_filter_gives_list_of_even_numbers};
char testFileName[] = {"linkedListTest.c"};
void _setup(){/*CALL_SETUP*/}
void _teardown(){/*CALL_TEARDOWN*/}
void fixtureSetup(){}
void fixtureTearDown(){}
//code to be updated ends

int testCount;
int passCount;
int currentTestFailed;

int assert_expr(int expr, const char* fileName, int lineNumber, const char* expression){
	if(expr) return 0;
	currentTestFailed = 1;
	printf("\t %s : failed at %s:%d\n",expression, fileName,lineNumber);
	return 1;
}
int assert_equal(int val1, int val2, const char* fileName, int lineNumber,const char* expr1,const char* expr2){
	if(val1 == val2) return 0;
	currentTestFailed = 1;
	printf("\t %d == %d: failed in assertEqual(%s,%s) at %s:%d\n",val1,val2,expr1,expr2, fileName,lineNumber);
	return 1;
}

void runTest(char* name, TestFn test){
	testCount++,currentTestFailed=0;
	printf("**  %s\n",name);
	_setup();
		test();
	_teardown();
	if(!currentTestFailed) passCount++;	
}
int main(int argc, char const *argv[]){		
	int i,total = sizeof(test)/sizeof(Test);	
	fixtureSetup();
	testCount=0,passCount=0;
	printf("**------ %s ------\n",testFileName);
	for (i = 0; i < total; ++i)
		runTest(test[i].name,test[i].fn);	
	printf("** Ran %d tests passed %d failed %d\n",testCount,passCount,testCount-passCount);
	fixtureTearDown();	
	return 0;
}